In [218]:
from scipy.spatial import distance as dist
import numpy as np

In [219]:
from imutils.perspective import four_point_transform
import imutils
import cv2
import re

In [220]:
def resize(image, width=None, height=None, inter=cv2.INTER_AREA):
    # initialize the dimensions of the image to be resized and
    # grab the image size
    dim = None
    (h, w) = image.shape[:2]

    # if both the width and height are None, then return the
    # original image
    if width is None and height is None:
        return image

    # check to see if the width is None
    if width is None:
        # calculate the ratio of the height and construct the
        # dimensions
        r = height / float(h)
        dim = (int(w * r), height)

    # otherwise, the height is None
    else:
        # calculate the ratio of the width and construct the
        # dimensions
        r = width / float(w)
        dim = (width, int(h * r))

    # resize the image
    resized = cv2.resize(image, dim, interpolation=inter)

    # return the resized image
    return resized

In [221]:
orig = cv2.imread('opening.jpg')
orig1 = cv2.imread("data/test/IMG_3708 5.18.41 AM.jpg")
image = orig.copy()
image1 = orig1.copy()
image = resize(image, width=500)
image1 = resize(image1, width=500)
cv2.imwrite('final_out1.jpg', image)
cv2.imwrite('final_out2.jpg', image1)
ratio = orig.shape[1] / float(image.shape[1])

In [222]:
print(ratio)

6.048


In [223]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray, (5, 5,), 0)
edged = cv2.Canny(blurred, 75, 200)

In [224]:
cv2.imwrite('final_edged.jpg', edged)

True

In [225]:
cnts = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

In [226]:
def grab_contours(cnts):
    # if the length the contours tuple returned by cv2.findContours
    # is '2' then we are using either OpenCV v2.4, v4-beta, or
    # v4-official
    if len(cnts) == 2:
        cnts = cnts[0]

    # if the length of the contours tuple is '3' then we are using
    # either OpenCV v3, v4-pre, or v4-alpha
    elif len(cnts) == 3:
        cnts = cnts[1]

    # otherwise OpenCV has changed their cv2.findContours return
    # signature yet again and I have no idea WTH is going on
    else:
        raise Exception(("Contours tuple must have length 2 or 3, "
            "otherwise OpenCV changed their cv2.findContours return "
            "signature yet again. Refer to OpenCV's documentation "
            "in that case"))

    # return the actual contours array
    return cnts

In [227]:
cnts = grab_contours(cnts)
#cnts = hull

In [228]:
cnts = sorted(cnts, key=cv2.contourArea, reverse=True)

In [229]:
print(cnts)

[array([[[170,  50]],

       [[169,  51]],

       [[168,  51]],

       [[166,  53]],

       [[165,  53]],

       [[164,  54]],

       [[164,  55]],

       [[163,  56]],

       [[163,  57]],

       [[162,  58]],

       [[162,  63]],

       [[161,  64]],

       [[161,  69]],

       [[160,  70]],

       [[160,  76]],

       [[159,  77]],

       [[159, 146]],

       [[158, 147]],

       [[158, 185]],

       [[157, 186]],

       [[157, 200]],

       [[158, 201]],

       [[158, 257]],

       [[157, 258]],

       [[157, 365]],

       [[156, 366]],

       [[156, 476]],

       [[155, 477]],

       [[155, 587]],

       [[154, 588]],

       [[154, 599]],

       [[155, 600]],

       [[155, 608]],

       [[156, 609]],

       [[156, 614]],

       [[157, 615]],

       [[157, 620]],

       [[158, 621]],

       [[158, 623]],

       [[159, 624]],

       [[159, 625]],

       [[160, 626]],

       [[160, 628]],

       [[161, 629]],

       [[161, 630]],

       [[

In [230]:
receiptCnt = None
# loop over the contours
for c in cnts:
    # approximate the contour
    peri = cv2.arcLength(c, True)
    approx = cv2.approxPolyDP(c, 0.02 * peri, True)
    print(approx)
    # if our approximated contour has four points, then we can
    # assume we have found the outline of the receipt
    if len(approx) == 4:
        receiptCnt = approx
        break
# if the receipt contour is empty then our script could not find the
# outline and we should be notified
print(receiptCnt)
if receiptCnt is None:
    raise Exception(("Could not find receipt outline. "
        "Try debugging your edge detection and contour steps."))

[[[170  50]]

 [[157 620]]

 [[344 633]]

 [[339  78]]]
[[[170  50]]

 [[157 620]]

 [[344 633]]

 [[339  78]]]


In [231]:
def order_points(pts):
    # sort the points based on their x-coordinates
    xSorted = pts[np.argsort(pts[:, 0]), :]

    # grab the left-most and right-most points from the sorted
    # x-roodinate points
    leftMost = xSorted[:2, :]
    rightMost = xSorted[2:, :]

    # now, sort the left-most coordinates according to their
    # y-coordinates so we can grab the top-left and bottom-left
    # points, respectively
    leftMost = leftMost[np.argsort(leftMost[:, 1]), :]
    (tl, bl) = leftMost

    # now that we have the top-left coordinate, use it as an
    # anchor to calculate the Euclidean distance between the
    # top-left and right-most points; by the Pythagorean
    # theorem, the point with the largest distance will be
    # our bottom-right point
    D = dist.cdist(tl[np.newaxis], rightMost, "euclidean")[0]
    (br, tr) = rightMost[np.argsort(D)[::-1], :]

    # return the coordinates in top-left, top-right,
    # bottom-right, and bottom-left order
    return np.array([tl, tr, br, bl], dtype="float32")

def four_point_transform(image, pts):
    # obtain a consistent order of the points and unpack them
    # individually
    rect = order_points(pts)
    (tl, tr, br, bl) = rect

    # compute the width of the new image, which will be the
    # maximum distance between bottom-right and bottom-left
    # x-coordiates or the top-right and top-left x-coordinates
    widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
    widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
    maxWidth = max(int(widthA), int(widthB))

    # compute the height of the new image, which will be the
    # maximum distance between the top-right and bottom-right
    # y-coordinates or the top-left and bottom-left y-coordinates
    heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
    heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
    maxHeight = max(int(heightA), int(heightB))

    # now that we have the dimensions of the new image, construct
    # the set of destination points to obtain a "birds eye view",
    # (i.e. top-down view) of the image, again specifying points
    # in the top-left, top-right, bottom-right, and bottom-left
    # order
    dst = np.array([
        [0, 0],
        [maxWidth - 1, 0],
        [maxWidth - 1, maxHeight - 1],
        [0, maxHeight - 1]], dtype="float32")

    # compute the perspective transform matrix and then apply it
    M = cv2.getPerspectiveTransform(rect, dst)
    warped = cv2.warpPerspective(image, M, (maxWidth, maxHeight))

    # return the warped image
    return warped

In [232]:
receipt = four_point_transform(orig1, receiptCnt.reshape(4, 2) * ratio)

In [233]:
cv2.imwrite('final_out.jpg', resize(receipt, width=500))

True